spring.application.name=GuideWeb
# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/travel_guide
spring.datasource.username=root
spring.datasource.password=Anishamysql2209006

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
